<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Case study: Using debrief for iterative R performance optimization • debrief</title>
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Case study: Using debrief for iterative R performance optimization">
<script src="https://cdn.jsdelivr.net/gh/posit-dev/supported-by-posit/js/badge.min.js" data-max-height="43" data-light-bg="#666f76" data-light-fg="#f9f9f9"></script>
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">debrief</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.1.0.9000</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><a class="dropdown-item" href="../articles/case-study-tidypredict.html">Case study: Using debrief for iterative R performance optimization</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/r-lib/debrief/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-article">




<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Case study: Using debrief for iterative R performance optimization</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/r-lib/debrief/blob/main/vignettes/case-study-tidypredict.Rmd" class="external-link"><code>vignettes/case-study-tidypredict.Rmd</code></a></small>
      <div class="d-none name"><code>case-study-tidypredict.Rmd</code></div>
    </div>

    
    
<div class="section level2">
<h2 id="about-this-case-study">About this case study<a class="anchor" aria-label="anchor" href="#about-this-case-study"></a>
</h2>
<p>This case study was conducted by Claude (an AI assistant) to optimize
tidypredict’s random forest parsing. Two important notes about the
debrief package usage:</p>
<ol style="list-style-type: decimal">
<li><p><strong>No prior knowledge</strong>: Claude had no prior
knowledge of the debrief package before this session. The package was
not part of Claude’s training data.</p></li>
<li><p><strong>No documentation lookup</strong>: Claude did not read
debrief’s documentation, README, or help files. The only information
provided was the user’s prompt showing the basic usage pattern
(<code>pv_print_debrief(p)</code>). All interpretation of the output was
done from first principles based on the section names and
content.</p></li>
<li><p><strong>Test-driven verification</strong>: After each
optimization, Claude ran the package’s existing test suite
(<code>devtools::test()</code>) to verify the changes didn’t break
functionality. All 38 relevant tests (ranger: 18, randomForest: 13,
partykit: 7) passed after the optimizations.</p></li>
</ol>
<p>This demonstrates that debrief’s output is self-explanatory enough to
guide optimization work without requiring prior familiarity with the
package. The section names (TOP FUNCTIONS BY SELF-TIME, HOT LINES,
MEMORY ALLOCATION) clearly communicate what each part shows, and the
“Next steps” suggestions in the output hinted at additional functions
available.</p>
</div>
<div class="section level2">
<h2 id="overview">Overview<a class="anchor" aria-label="anchor" href="#overview"></a>
</h2>
<p>This case study demonstrates how the <strong>debrief</strong> package
can guide iterative performance optimization in R. We use tidypredict’s
random forest parsing as a real-world example, achieving a <strong>331x
speedup</strong> through systematic profiling and targeted fixes.</p>
</div>
<div class="section level2">
<h2 id="problem-statement">Problem statement<a class="anchor" aria-label="anchor" href="#problem-statement"></a>
</h2>
<p><a href="https://github.com/tidymodels/orbital/issues/83" class="external-link">tidymodels/orbital#83</a>
reported that parsing random forest models in tidypredict takes 45+
seconds for a single tree. We rolled back to the problematic version
(commit <code>0dde432</code>) to investigate.</p>
<div class="section level3">
<h3 id="user-prompt">User prompt<a class="anchor" aria-label="anchor" href="#user-prompt"></a>
</h3>
<p>The user provided the following instructions to guide the profiling
session:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode md"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a>profile the tidypredict_fit call in the following code.</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>library(tidymodels)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a>library(orbital)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a>rec_spec &lt;- recipe(Sale_Price ~ ., data = ames) |&gt;</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a>  step_normalize(all_numeric_predictors()) |&gt;</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a>  step_dummy(all_nominal_predictors())</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a>mod_spec &lt;- rand_forest("regression", trees = 1)</span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a>wf_spec &lt;- workflow(rec_spec, mod_spec)</span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a>wf_fit &lt;- fit(wf_spec, ames)</span>
<span id="cb1-13"><a href="#cb1-13" tabindex="-1"></a>rf_tree &lt;- extract_fit_engine(wf_fit)</span>
<span id="cb1-14"><a href="#cb1-14" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" tabindex="-1"></a>tmp &lt;- tidypredict_fit(rf_tree)</span>
<span id="cb1-16"><a href="#cb1-16" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" tabindex="-1"></a>I want you to use the profvis and debrief package to iteratively make improvements to the function</span>
<span id="cb1-18"><a href="#cb1-18" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" tabindex="-1"></a>library(profvis)</span>
<span id="cb1-20"><a href="#cb1-20" tabindex="-1"></a>library(debrief)</span>
<span id="cb1-21"><a href="#cb1-21" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" tabindex="-1"></a><span class="fu"># Profile some code</span></span>
<span id="cb1-23"><a href="#cb1-23" tabindex="-1"></a>p &lt;- profvis({</span>
<span id="cb1-24"><a href="#cb1-24" tabindex="-1"></a>  # your code here</span>
<span id="cb1-25"><a href="#cb1-25" tabindex="-1"></a>})</span>
<span id="cb1-26"><a href="#cb1-26" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" tabindex="-1"></a>pv_print_debrief(p)</span></code></pre></div>
<p>This prompt established the workflow: profile with profvis, analyze
with <code><a href="../reference/pv_print_debrief.html">pv_print_debrief()</a></code>, optimize, and repeat.</p>
</div>
</div>
<div class="section level2">
<h2 id="iteration-1-initial-profiling">Iteration 1: Initial profiling<a class="anchor" aria-label="anchor" href="#iteration-1-initial-profiling"></a>
</h2>
<div class="section level3">
<h3 id="running-debrief">Running debrief<a class="anchor" aria-label="anchor" href="#running-debrief"></a>
</h3>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://profvis.r-lib.org/reference/profvis.html" class="external-link">profvis</a></span><span class="op">(</span><span class="op">{</span></span>
<span>  <span class="va">tmp</span> <span class="op">&lt;-</span> <span class="fu">tidypredict_fit</span><span class="op">(</span><span class="va">rf_tree</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="../reference/pv_print_debrief.html">pv_print_debrief</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span></span></code></pre></div>
</div>
<div class="section level3">
<h3 id="debrief-output-key-sections">Debrief output (key sections)<a class="anchor" aria-label="anchor" href="#debrief-output-key-sections"></a>
</h3>
<pre><code>## PROFILING SUMMARY

Total time: 47340 ms (4734 samples @ 10 ms interval)

### TOP FUNCTIONS BY SELF-TIME
 15180 ms ( 32.1%)  [.data.frame
  5280 ms ( 11.2%)  &lt;GC&gt;
  4220 ms (  8.9%)  sys.call
  3950 ms (  8.3%)  [[.data.frame

### HOT LINES (by self-time)
 12710 ms ( 26.8%)  /R/model-ranger.R:6
                   row &lt;- tree[tree$nodeID == j, ]
  2880 ms (  6.1%)  /R/model-ranger.R:7
                   lc &lt;- row["leftChild"][[1]] == find
  2580 ms (  5.4%)  /R/model-ranger.R:8
                   lr &lt;- row["rightChild"][[1]] == find

### MEMORY ALLOCATION (by line)
15655.00 MB /R/model-ranger.R:6
            row &lt;- tree[tree$nodeID == j, ]
 3450.47 MB /R/model-ranger.R:7
            lc &lt;- row["leftChild"][[1]] == find</code></pre>
</div>
<div class="section level3">
<h3 id="how-i-interpreted-this-output">How I interpreted this output<a class="anchor" aria-label="anchor" href="#how-i-interpreted-this-output"></a>
</h3>
<ol style="list-style-type: decimal">
<li><p><strong>TOP FUNCTIONS BY SELF-TIME</strong> showed
<code>[.data.frame</code> at 32.1% - this is the data.frame subsetting
operator, suggesting repeated data.frame operations are the
culprit.</p></li>
<li><p><strong>HOT LINES</strong> pinpointed the exact line:
<code>row &lt;- tree[tree$nodeID == j, ]</code> consuming 26.8% of total
time. This single line was the primary bottleneck.</p></li>
<li><p><strong>MEMORY ALLOCATION</strong> revealed this same line was
allocating 15.6 GB - explaining the high GC time (11.2%). Each
subsetting operation creates a new data.frame copy.</p></li>
<li><p><strong>The pattern</strong>: Line 6 is inside a loop (indicated
by the variable <code>j</code>). Filtering a data.frame with
<code>tree[tree$nodeID == j, ]</code> is O(n) per call. In a loop, this
becomes O(n^2).</p></li>
</ol>
</div>
<div class="section level3">
<h3 id="optimization-applied">Optimization applied<a class="anchor" aria-label="anchor" href="#optimization-applied"></a>
</h3>
<p>Pre-extract columns as vectors and use direct indexing:</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Before (O(n) per lookup):</span></span>
<span><span class="va">row</span> <span class="op">&lt;-</span> <span class="va">tree</span><span class="op">[</span><span class="va">tree</span><span class="op">$</span><span class="va">nodeID</span> <span class="op">==</span> <span class="va">j</span>, <span class="op">]</span></span>
<span><span class="va">lc</span> <span class="op">&lt;-</span> <span class="va">row</span><span class="op">[</span><span class="st">"leftChild"</span><span class="op">]</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span> <span class="op">==</span> <span class="va">find</span></span>
<span></span>
<span><span class="co"># After (O(1) per lookup):</span></span>
<span><span class="va">idx</span> <span class="op">&lt;-</span> <span class="va">j</span> <span class="op">+</span> <span class="fl">1L</span></span>
<span><span class="va">lc</span> <span class="op">&lt;-</span> <span class="va">left_child</span><span class="op">[</span><span class="va">idx</span><span class="op">]</span> <span class="op">==</span> <span class="va">find</span></span></code></pre></div>
</div>
<div class="section level3">
<h3 id="result">Result<a class="anchor" aria-label="anchor" href="#result"></a>
</h3>
<table class="table">
<thead><tr class="header">
<th align="left">Metric</th>
<th align="right">Before</th>
<th align="right">After</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Time</td>
<td align="right">47,340 ms</td>
<td align="right">280 ms</td>
</tr>
<tr class="even">
<td align="left">Memory</td>
<td align="right">~18 GB</td>
<td align="right">~20 MB</td>
</tr>
<tr class="odd">
<td align="left">Speedup</td>
<td align="right">-</td>
<td align="right"><strong>169x</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="section level2">
<h2 id="iteration-2-finding-the-next-bottleneck">Iteration 2: Finding the next bottleneck<a class="anchor" aria-label="anchor" href="#iteration-2-finding-the-next-bottleneck"></a>
</h2>
<div class="section level3">
<h3 id="debrief-output-after-first-optimization">Debrief output after first optimization<a class="anchor" aria-label="anchor" href="#debrief-output-after-first-optimization"></a>
</h3>
<pre><code>## PROFILING SUMMARY

Total time: 290 ms (29 samples @ 10 ms interval)

### TOP FUNCTIONS BY SELF-TIME
    60 ms ( 20.7%)  is.na
    20 ms (  6.9%)  .f
    20 ms (  6.9%)  if (lc || lr) {
    20 ms (  6.9%)  lc &lt;- left_child[idx] == find

### HOT LINES (by self-time)
    60 ms ( 20.7%)  /R/model-ranger.R:16
                   if (is.na(lc)) {
    20 ms (  6.9%)  /R/model-ranger.R:14
                   lc &lt;- left_child[idx] == find
    20 ms (  6.9%)  /R/model-ranger.R:22
                   if (lc || lr) {</code></pre>
</div>
<div class="section level3">
<h3 id="how-i-interpreted-this-output-1">How I interpreted this output<a class="anchor" aria-label="anchor" href="#how-i-interpreted-this-output-1"></a>
</h3>
<ol style="list-style-type: decimal">
<li><p><strong>TOP FUNCTIONS BY SELF-TIME</strong> now showed
<code>is.na</code> as the top consumer at 20.7%. The bottleneck shifted
from data.frame operations to NA checking.</p></li>
<li><p><strong>HOT LINES</strong> showed the <code>is.na</code> checks
on lines 16 and 19 were being called repeatedly in the loop.</p></li>
<li><p><strong>The insight</strong>: The code was searching for parent
nodes by iterating from <code>node_id</code> down to 0, checking each
potential parent. This linear search could be replaced with a direct
lookup.</p></li>
</ol>
</div>
<div class="section level3">
<h3 id="optimization-applied-1">Optimization applied<a class="anchor" aria-label="anchor" href="#optimization-applied-1"></a>
</h3>
<p>Pre-compute parent relationships once, then traverse directly:</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Before: Linear search for parent</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">j</span> <span class="kw">in</span> <span class="va">node_id</span><span class="op">:</span><span class="fl">0</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">idx</span> <span class="op">&lt;-</span> <span class="va">j</span> <span class="op">+</span> <span class="fl">1L</span></span>
<span>  <span class="va">lc</span> <span class="op">&lt;-</span> <span class="va">left_child</span><span class="op">[</span><span class="va">idx</span><span class="op">]</span> <span class="op">==</span> <span class="va">find</span></span>
<span>  <span class="va">lr</span> <span class="op">&lt;-</span> <span class="va">right_child</span><span class="op">[</span><span class="va">idx</span><span class="op">]</span> <span class="op">==</span> <span class="va">find</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html" class="external-link">is.na</a></span><span class="op">(</span><span class="va">lc</span><span class="op">)</span><span class="op">)</span> <span class="va">lc</span> <span class="op">&lt;-</span> <span class="cn">FALSE</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html" class="external-link">is.na</a></span><span class="op">(</span><span class="va">lr</span><span class="op">)</span><span class="op">)</span> <span class="va">lr</span> <span class="op">&lt;-</span> <span class="cn">FALSE</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="va">lc</span> <span class="op">||</span> <span class="va">lr</span><span class="op">)</span> <span class="op">{</span> <span class="va">...</span> <span class="op">}</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># After: Direct traversal using parent lookup</span></span>
<span><span class="kw">while</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html" class="external-link">is.na</a></span><span class="op">(</span><span class="va">parent</span><span class="op">[</span><span class="va">current</span> <span class="op">+</span> <span class="fl">1L</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">current</span> <span class="op">&lt;-</span> <span class="va">parent</span><span class="op">[</span><span class="va">current</span> <span class="op">+</span> <span class="fl">1L</span><span class="op">]</span></span>
<span>  <span class="va">path</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">path</span>, <span class="va">current</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
</div>
<div class="section level3">
<h3 id="result-1">Result<a class="anchor" aria-label="anchor" href="#result-1"></a>
</h3>
<table class="table">
<thead><tr class="header">
<th align="left">Metric</th>
<th align="right">Before</th>
<th align="left">After</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Time</td>
<td align="right">290 ms</td>
<td align="left">160 ms</td>
</tr>
<tr class="even">
<td align="left">Speedup</td>
<td align="right">-</td>
<td align="left"><strong>45% faster</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="section level2">
<h2 id="iteration-3-diminishing-returns">Iteration 3: Diminishing returns<a class="anchor" aria-label="anchor" href="#iteration-3-diminishing-returns"></a>
</h2>
<div class="section level3">
<h3 id="debrief-output-using-10-trees-for-better-sampling">Debrief output (using 10 trees for better sampling)<a class="anchor" aria-label="anchor" href="#debrief-output-using-10-trees-for-better-sampling"></a>
</h3>
<pre><code>## PROFILING SUMMARY

Total time: 1650 ms (165 samples @ 10 ms interval)

### TOP FUNCTIONS BY SELF-TIME
   280 ms ( 17.0%)  &lt;GC&gt;
   200 ms ( 12.1%)  enexpr
   110 ms (  6.7%)  reduce_impl

### HOT LINES (by self-time)
    60 ms (  3.6%)  /R/model-rf.R:80
                   if (.x$op == "less") i &lt;- expr(!!sym(.x$col) &lt; !!.x$val)
    30 ms (  1.8%)  /R/model-rf.R:78
                   if (.x$op == "more") i &lt;- expr(!!sym(.x$col) &gt; !!.x$val)

### TOP FUNCTIONS BY TOTAL TIME
  1020 ms ( 61.8%)  path_formulas
   500 ms ( 30.3%)  expr</code></pre>
</div>
<div class="section level3">
<h3 id="how-i-interpreted-this-output-2">How I interpreted this output<a class="anchor" aria-label="anchor" href="#how-i-interpreted-this-output-2"></a>
</h3>
<ol style="list-style-type: decimal">
<li><p><strong>TOP FUNCTIONS BY TOTAL TIME</strong> showed
<code>path_formulas</code> at 61.8% - the bottleneck shifted to formula
building.</p></li>
<li><p><strong>HOT LINES</strong> showed multiple if-statements checking
<code>.x$op</code> repeatedly (lines 78-81).</p></li>
<li><p><strong>TOP FUNCTIONS BY SELF-TIME</strong> showed
<code>enexpr</code> (expression building) and <code>reduce_impl</code>
as top consumers - these are doing useful work.</p></li>
<li><p><strong>The insight</strong>: The if-chain could be replaced with
<code><a href="https://rdrr.io/r/base/switch.html" class="external-link">switch()</a></code>, but we’re now optimizing code that’s doing
inherent work. Further gains will be marginal.</p></li>
</ol>
</div>
<div class="section level3">
<h3 id="optimization-applied-2">Optimization applied<a class="anchor" aria-label="anchor" href="#optimization-applied-2"></a>
</h3>
<p>Replace if-chain with switch statement:</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Before:</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">op</span> <span class="op">==</span> <span class="st">"more"</span><span class="op">)</span> <span class="va">i</span> <span class="op">&lt;-</span> <span class="fu">expr</span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="fu">sym</span><span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">col</span><span class="op">)</span> <span class="op">&gt;</span> <span class="op">!</span><span class="op">!</span><span class="va">.x</span><span class="op">$</span><span class="va">val</span><span class="op">)</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">op</span> <span class="op">==</span> <span class="st">"more-equal"</span><span class="op">)</span> <span class="va">i</span> <span class="op">&lt;-</span> <span class="fu">expr</span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="fu">sym</span><span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">col</span><span class="op">)</span> <span class="op">&gt;=</span> <span class="op">!</span><span class="op">!</span><span class="va">.x</span><span class="op">$</span><span class="va">val</span><span class="op">)</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">op</span> <span class="op">==</span> <span class="st">"less"</span><span class="op">)</span> <span class="va">i</span> <span class="op">&lt;-</span> <span class="fu">expr</span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="fu">sym</span><span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">col</span><span class="op">)</span> <span class="op">&lt;</span> <span class="op">!</span><span class="op">!</span><span class="va">.x</span><span class="op">$</span><span class="va">val</span><span class="op">)</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">op</span> <span class="op">==</span> <span class="st">"less-equal"</span><span class="op">)</span> <span class="va">i</span> <span class="op">&lt;-</span> <span class="fu">expr</span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="fu">sym</span><span class="op">(</span><span class="va">.x</span><span class="op">$</span><span class="va">col</span><span class="op">)</span> <span class="op">&lt;=</span> <span class="op">!</span><span class="op">!</span><span class="va">.x</span><span class="op">$</span><span class="va">val</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># After:</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/switch.html" class="external-link">switch</a></span><span class="op">(</span></span>
<span>  <span class="va">.x</span><span class="op">$</span><span class="va">op</span>,</span>
<span>  <span class="st">"more"</span> <span class="op">=</span> <span class="fu">expr</span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="va">col_sym</span> <span class="op">&gt;</span> <span class="op">!</span><span class="op">!</span><span class="va">val</span><span class="op">)</span>,</span>
<span>  <span class="st">"more-equal"</span> <span class="op">=</span> <span class="fu">expr</span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="va">col_sym</span> <span class="op">&gt;=</span> <span class="op">!</span><span class="op">!</span><span class="va">val</span><span class="op">)</span>,</span>
<span>  <span class="st">"less"</span> <span class="op">=</span> <span class="fu">expr</span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="va">col_sym</span> <span class="op">&lt;</span> <span class="op">!</span><span class="op">!</span><span class="va">val</span><span class="op">)</span>,</span>
<span>  <span class="st">"less-equal"</span> <span class="op">=</span> <span class="fu">expr</span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="va">col_sym</span> <span class="op">&lt;=</span> <span class="op">!</span><span class="op">!</span><span class="va">val</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
</div>
<div class="section level3">
<h3 id="result-2">Result<a class="anchor" aria-label="anchor" href="#result-2"></a>
</h3>
<p>Minor improvement (~4%). The remaining time is in expression building
which is inherent to the task.</p>
</div>
</div>
<div class="section level2">
<h2 id="why-i-only-used-pv_print_debrief">Why I only used <code>pv_print_debrief()</code><a class="anchor" aria-label="anchor" href="#why-i-only-used-pv_print_debrief"></a>
</h2>
<p>The debrief package offers several functions, and
<code><a href="../reference/pv_print_debrief.html">pv_print_debrief()</a></code> suggests others at the end of its
output:</p>
<pre><code><span><span class="co">### Next steps</span></span>
<span><span class="fu"><a href="../reference/pv_source_context.html">pv_source_context</a></span><span class="op">(</span><span class="va">p</span>, <span class="st">"/R/model-ranger.R"</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/pv_suggestions.html">pv_suggestions</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/pv_focus.html">pv_focus</a></span><span class="op">(</span><span class="va">p</span>, <span class="st">".f"</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/pv_help.html">pv_help</a></span><span class="op">(</span><span class="op">)</span></span></code></pre>
<div class="section level3">
<h3 id="functions-i-didnt-use">Functions I didn’t use<a class="anchor" aria-label="anchor" href="#functions-i-didnt-use"></a>
</h3>
<table class="table">
<colgroup>
<col width="12%">
<col width="23%">
<col width="64%">
</colgroup>
<thead><tr class="header">
<th align="left">Function</th>
<th align="left">Purpose</th>
<th align="left">Why I skipped it</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><code><a href="../reference/pv_source_context.html">pv_source_context()</a></code></td>
<td align="left">Shows more code context around hot lines</td>
<td align="left">I was already reading full source files directly. Once
HOT LINES said “line 6 in model-ranger.R”, I just read that file.</td>
</tr>
<tr class="even">
<td align="left"><code><a href="../reference/pv_suggestions.html">pv_suggestions()</a></code></td>
<td align="left">Provides automated optimization suggestions</td>
<td align="left">The bottlenecks were obvious enough (32% in
<code>[.data.frame</code>, 15.6 GB on one line) that I could diagnose
the issue myself.</td>
</tr>
<tr class="odd">
<td align="left"><code><a href="../reference/pv_focus.html">pv_focus()</a></code></td>
<td align="left">Filters analysis to a specific function</td>
<td align="left">The initial output was already clear about where
problems were. No need to drill down.</td>
</tr>
</tbody>
</table>
</div>
<div class="section level3">
<h3 id="when-pv_print_debrief-alone-is-sufficient">When <code>pv_print_debrief()</code> alone is sufficient<a class="anchor" aria-label="anchor" href="#when-pv_print_debrief-alone-is-sufficient"></a>
</h3>
<p>The single function was enough because:</p>
<ol style="list-style-type: decimal">
<li>
<strong>HOT LINES gave exact locations</strong> - File path and line
number meant I could go straight to the problem code</li>
<li>
<strong>MEMORY ALLOCATION correlated with time</strong> - The same
lines appeared in both sections, confirming the diagnosis</li>
<li>
<strong>Patterns were recognizable</strong> - Data.frame subsetting
in a loop is a known anti-pattern</li>
</ol>
</div>
<div class="section level3">
<h3 id="when-to-use-the-other-functions">When to use the other functions<a class="anchor" aria-label="anchor" href="#when-to-use-the-other-functions"></a>
</h3>
<p>I would reach for additional functions if:</p>
<ul>
<li>
<strong>Diffuse profile</strong> - Time spread across many functions
without a clear culprit</li>
<li>
<strong>Complex call paths</strong> - Need to understand how a
bottleneck is reached from different entry points</li>
<li>
<strong>Unfamiliar codebase</strong> -
<code><a href="../reference/pv_source_context.html">pv_source_context()</a></code> would help see surrounding code without
switching tools</li>
<li>
<strong>Stuck on diagnosis</strong> - <code><a href="../reference/pv_suggestions.html">pv_suggestions()</a></code>
might catch patterns I missed</li>
</ul>
</div>
</div>
<div class="section level2">
<h2 id="final-results">Final results<a class="anchor" aria-label="anchor" href="#final-results"></a>
</h2>
<table class="table">
<colgroup>
<col width="32%">
<col width="17%">
<col width="14%">
<col width="35%">
</colgroup>
<thead><tr class="header">
<th align="left">Stage</th>
<th align="right">Time</th>
<th align="right">Speedup</th>
<th align="left">Key debrief insight</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Original</td>
<td align="right">47,340 ms</td>
<td align="right">1x</td>
<td align="left">
<code>[.data.frame</code> at 32%</td>
</tr>
<tr class="even">
<td align="left">After vectorization</td>
<td align="right">280 ms</td>
<td align="right">169x</td>
<td align="left">
<code>is.na</code> now at 20%</td>
</tr>
<tr class="odd">
<td align="left">After parent lookup</td>
<td align="right">160 ms</td>
<td align="right">296x</td>
<td align="left">
<code>path_formulas</code> at 60%</td>
</tr>
<tr class="even">
<td align="left">After switch</td>
<td align="right"><strong>143 ms</strong></td>
<td align="right"><strong>331x</strong></td>
<td align="left">Diminishing returns</td>
</tr>
</tbody>
</table>
</div>
  </main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>



    <footer><div class="pkgdown-footer-left">
  <p>Developed by Emil Hvitfeldt, Posit Software, PBC.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
